<a href="https://colab.research.google.com/github/Sidney-130/learning-pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Learning tensorflow




In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
#Maths

In [ ]:
tensor_A = torch.tensor([1,2,3])
tensor_A

tensor([1, 2, 3])

In [ ]:
tensor_B = torch.tensor([5,6,7])
tensor_B

tensor([5, 6, 7])

In [ ]:
tensor_A.add_(tensor_B)
tensor_A

tensor([11, 14, 17])

In [ ]:
#Neural network

In [20]:
class Model(nn.Module):
  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__()
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)
  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x

In [21]:
#Pick a random seed for randomization
torch.manual_seed(50)
#Create an insatnce of model
model = Model()
